font_family RobotoMono Nerd Font
font_size 16
confirm_os_window_close 0

# Black
color0  #000000
color8  #4c4f69

# Red
color1  #d20f39
color9  #e78284

# Green
color2  #40a02b
color10 #a6d189

# Yellow
color3  #df8e1d
color11 #e5c890

# Blue
color4  #1e66f5
color12 #8caaee

# Magenta
color5  #8839ef
color13 #ca9ee6

# Cyan
color6  #209fb5
color14 #85c1dc

# White
color7  #c6d0f5
color15 #ffffff
