alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias la='ls -a'
alias ll='ls -hAl'
alias lt='ls -hAlt'

alias ls..='ls ..'
alias la..='la ..'
alias ll..='ll ..'
alias lt..='lt ..'
alias cd..='cd ..'

alias cls='clear'
alias view='vim -R'
alias bat='BAT0=/sys/class/power_supply/BAT0 [ -d BAT0 ] && printf "%s%% - %s\n" $(cat $BAT0/capacity) $(cat $BAT0/status) || echo "Battery not found"'
alias font-list='fc-list | cut -d ":" -f 2- | cut -d "," -f 1 | sort -u'
alias code='code --touch-events'
