HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd extendedglob nomatch prompt_subst
unsetopt beep notify
bindkey -v
zstyle :compinstall filename '/home/dan/.zshrc'

autoload -Uz compinit vcs_info
compinit

zstyle ':vcs_info:git:*' formats ' (%b%u) '
zstyle ':vcs_info:git:*' actionformats ' (%b|%a%u) '

precmd_functions+=(vcs_info)

PROMPT='%(!\%F{red}:\%F{green})%n%B%F{black}@%m:%b%F{cyan}%~%F{yellow}${vcs_info_msg_0_}%(!\%F{red}#:\%F{green}$)%f '
