HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=black,bold'

setopt autocd extendedglob nomatch prompt_subst
unsetopt beep notify

bindkey -v
bindkey -M viins '^F' autosuggest-accept

autoload -Uz compinit vcs_info
compinit

zstyle :compinstall filename '/home/dan/.zshrc'
zstyle ':vcs_info:git:*' formats ' (%b%u) '
zstyle ':vcs_info:git:*' actionformats ' (%b|%a%u) '
zstyle ':completion:*' menu select

precmd_functions+=(vcs_info)
PROMPT='%(!\%F{red}:\%F{green})%n%B%F{black}@%m:%b%F{cyan}%~%F{yellow}${vcs_info_msg_0_}%(!\%F{red}#:\%F{green}$)%f '

source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
