# History
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=black,bold'

# Shell options
setopt autocd extendedglob nomatch prompt_subst
unsetopt beep notify

# Keybindings
bindkey -v
bindkey -M viins '^F' autosuggest-accept

# Completion
autoload -Uz compinit && compinit
zstyle :compinstall filename '/home/dan/.zshrc'
zstyle ':completion:*' menu select

# Set global vars to be used in PROMPT (currently only setting a single var, but can set multiple)
typeset -g prompt_var
set_prompt_vars() {

  # If not in a git repo, just use built-in %~ and exit
  local root
  if ! root=$(git rev-parse --show-toplevel 2>/dev/null); then
    prompt_var="%F{cyan}%~%f"
    return
  fi

  # Get working directory while highlighting repo's root directory
  local repo="${root##*/}"
  local left="${PWD%%/$repo*}/"; left="${left/#$HOME/~}"
  local right="${PWD#*/$repo}"
  local prompt_pwd="%F{cyan}${left}%B${repo}%b${right}%f"

  # Retrieve git info
  local info=$(git -C "$root" status --porcelain=2 --branch 2>/dev/null)

  # Current branch's name
  local branch
  if [[ $info =~ $'\n# branch\\.head ([^\n]+)' ]]; then
    branch="%F{yellow}${match[1]}%f"
  fi

  # Get number of commits local repo is ahead and behind of upstream
  local delta
  if [[ $info =~ $'\n# branch\\.ab \\+([0-9]+) -([0-9]+)' ]]; then
    (( match[1] )) && delta="%F{green}↑${match[1]}%f"
    (( match[2] )) && delta+="%F{red}↓${match[2]}%f"
  fi

  # Get number of items each that are staged, unstaged, or untracked
  local staged=0 unstaged=0 untracked=0
  while IFS= read -r line; do
    case $line in
      1\ *|2\ *)
        [[ "${line[3]}" != "." ]] && (( staged++ ))
        [[ "${line[4]}" != "." ]] && (( unstaged++ ))
        ;;
      \?\ *)
        (( untracked++ ))
        ;;
    esac
  done <<< $info

  # Set prompt_var (puts it all together with proper spacing)
  local flags
  (( staged )) && flags+="+"
  (( unstaged )) && flags+="!"
  (( untracked )) && flags+="?"
  [[ -n "$flags" ]] && flags="%B%F{red}${flags}%f%b"
  [[ -n "${delta}${flags}" ]] && flags=" ${delta}${flags}"
  prompt_var="${prompt_pwd} ${branch}${flags}"

#  [[ -s $root/logs/regs/stash ]] && prompt_flags+="*"
#  prompt_flags="%B%F{red}${prompt_flags}%f%b"

}

# Set prompt variables
prompt_user='%(!.%F{red}.%F{green})%n%f'
prompt_host='%B%F{black}%m%f%b'
prompt_terminator='%(?.%F{green}.%F{red})%(!.#.%%)%f'
set_prompt_vars

# Set prompt
#chpwd_functions+=(set_prompt_vars)
precmd_functions+=(set_prompt_vars)
PROMPT='${prompt_user} ${prompt_host} ${prompt_var} ${prompt_terminator} '

# Plugins
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
